### ISSUE TITLE
Kibana failed to start

### ISSUE THREAD

**Issue by panyang1217** [elastic/azure-marketplace#177]
After template deployed, the kibana service can not start successfully.
There is nothing in /var/log/kibana.log.
This is the message in /var/log/syslog:

> Apr 12 10:13:19 kibana systemd[1]: kibana.service: Failed with result 'exit-code'.
> Apr 12 10:13:19 kibana systemd[1]: kibana.service: Service hold-off time over, scheduling restart.
> Apr 12 10:13:19 kibana systemd[1]: Stopped Kibana.
> Apr 12 10:13:19 kibana systemd[1]: Started Kibana.
> Apr 12 10:13:23 kibana systemd[1]: kibana.service: Main process exited, code=exited, status=64/n/a
> Apr 12 10:13:23 kibana systemd[1]: kibana.service: Unit entered failed state.
> Apr 12 10:13:23 kibana systemd[1]: kibana.service: Failed with result 'exit-code'.
> Apr 12 10:13:24 kibana systemd[1]: kibana.service: Service hold-off time over, scheduling restart.
> Apr 12 10:13:24 kibana systemd[1]: Stopped Kibana.
> Apr 12 10:13:24 kibana systemd[1]: Started Kibana.
> Apr 12 10:13:28 kibana systemd[1]: kibana.service: Main process exited, code=exited, status=64/n/a
> Apr 12 10:13:28 kibana systemd[1]: kibana.service: Unit entered failed state.
> Apr 12 10:13:28 kibana systemd[1]: kibana.service: Failed with result 'exit-code'.
> Apr 12 10:13:28 kibana systemd[1]: kibana.service: Service hold-off time over, scheduling restart.
> Apr 12 10:13:28 kibana systemd[1]: Stopped Kibana.
> Apr 12 10:13:28 kibana systemd[1]: Started Kibana.
> Apr 12 10:13:33 kibana systemd[1]: kibana.service: Main process exited, code=exited, status=64/n/a
> Apr 12 10:13:33 kibana systemd[1]: kibana.service: Unit entered failed state.
> Apr 12 10:13:33 kibana systemd[1]: kibana.service: Failed with result 'exit-code'.
> Apr 12 10:13:33 kibana systemd[1]: kibana.service: Service hold-off time over, scheduling restart.
> Apr 12 10:13:33 kibana systemd[1]: Stopped Kibana.
> Apr 12 10:13:33 kibana systemd[1]: Started Kibana.
> Apr 12 10:13:37 kibana systemd[1]: kibana.service: Main process exited, code=exited, status=64/n/a
> Apr 12 10:13:37 kibana systemd[1]: kibana.service: Unit entered failed state.
> Apr 12 10:13:37 kibana systemd[1]: kibana.service: Failed with result 'exit-code'.
> Apr 12 10:13:37 kibana systemd[1]: kibana.service: Service hold-off time over, scheduling restart.
> Apr 12 10:13:37 kibana systemd[1]: Stopped Kibana.
> Apr 12 10:13:37 kibana systemd[1]: Started Kibana.

**Comment by panyang1217** [comment]
Resolved. 
The reason is that x-pack installation has not successed, though the install script has exit with no error.
There is a internet problem when downloading the x-pack plugin.

**Comment by russcam** [comment]
@panyang1217 This is likely the same issue as #169 whereby DNS does not resolve artifacts.elastic.co sometimes when running the installation script. There should be a number of retries and the script should exit with a non zero code in the case of failure.
